import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { URL } from 'node:url';
import { compile, forbidden, parseJSON } from './build-content.mjs';
const original=JSON.parse(readFileSync(new URL('../content/reflections.json',import.meta.url)));
const sources=JSON.parse(readFileSync(new URL('../content/sources.json',import.meta.url)));
function changed(mutate) { const input=structuredClone(original); const registry=structuredClone(sources); mutate(input,registry); return ()=>compile(input,registry); }
test('approved 48 records preserve exact copy, IDs, order and UTF-8',()=>{ const output=compile(original,sources); const records=JSON.parse(output.json); assert.equal(records.length,48); assert.deepEqual(records,original.reflections.map(({id,teaser,reflection})=>({id,teaser,reflection}))); assert.match(output.filename,/^reflections\.[a-f0-9]{16}\.json$/); for(const record of records) assert.deepEqual(Object.keys(record),['id','teaser','reflection']); });
test('deterministic hash changes only for publishable content',()=>{const a=compile(original,sources); assert.deepEqual(a,compile(original,sources)); const b=structuredClone(original); b.reflections[0].lifeSketch='Private replacement.'; assert.deepEqual(a,compile(b,sources)); b.reflections[0].reflection+=' I remember.'; assert.notEqual(a.filename,compile(b,sources).filename);});
test('runtime assets exclude metadata keys and private marker values',()=>{const input=structuredClone(original); input.reflections[0].lifeSketch='PRIVATE_SENTINEL_4f55'; input.reflections[0].causeOfDeath='PRIVATE_CAUSE_4f55'; const output=compile(input,sources); const assets=output.json+output.types; for(const name of forbidden) assert.ok(!assets.includes(name)); assert.ok(!assets.includes('PRIVATE_')); for(const record of sources.sources) { if(record.url) assert.ok(!assets.includes(record.url)); } });
const fixtures=[
 ['missing root',x=>delete x.fictional],['wrong version',x=>x.schemaVersion=2],['false fiction',x=>x.fictional=false],['wrong count',x=>x.reflections.pop()],['null record',x=>x.reflections[0]=null],['missing prose',x=>delete x.reflections[0].reflection],['extra property',x=>x.reflections[0].secret='bad'],['empty sketch',x=>x.reflections[0].lifeSketch=''],['wrong type',x=>x.reflections[0].teaser=5],['duplicate id',x=>x.reflections[1].id=x.reflections[0].id],['unknown id',x=>x.reflections[0].id='postponement-07'],['theme mismatch',x=>x.reflections[0].theme='connection'],['bad tone',x=>x.reflections[0].tone='happy'],['empty cues',x=>x.reflections[0].activityCues=[]],['invalid cue',x=>x.reflections[0].propCues=['gun']],['bad source',x=>x.reflections[0].sourceRefs=['S99']],['duplicate source',(_,s)=>s.sources[1].id=s.sources[0].id],['short body',x=>x.reflections[0].reflection='Only three words.'],['long body',x=>x.reflections[0].reflection='word '.repeat(60)+'word.'],['long teaser',x=>{x.reflections[0].teaser='word '.repeat(16)+'word.';x.reflections[0].reflection=x.reflections[0].teaser+' '+ 'word '.repeat(5)+'end.';}],['wrong prefix',x=>x.reflections[0].teaser='Not the first sentence.'],['multiple sentences as teaser',x=>{x.reflections[0].teaser='One. Two.';x.reflections[0].reflection='One. Two. '+ 'word '.repeat(20)+'end.';}],['no terminal punctuation',x=>{x.reflections[0].teaser='Only words';x.reflections[0].reflection='Only words '+ 'word '.repeat(20)+'end';}],['duplicate full text',x=>{x.reflections[1].reflection=x.reflections[0].reflection;x.reflections[1].teaser=x.reflections[0].teaser;}]
];
for(const [name,mutate] of fixtures) test('rejects '+name,()=>assert.throws(changed(mutate)));
test('malformed JSON is intentional diagnostic',()=>assert.throws(()=>parseJSON('{','fixture'),/fixture: invalid JSON/));
test('word boundaries 20/60 and 16-word teaser are inclusive',()=>{for(const total of [20,60]){const input=structuredClone(original); const teaser=Array(16).fill('a').join(' ')+'.';input.reflections[0].teaser=teaser;input.reflections[0].reflection=teaser+' '+Array(total-16).fill('b').join(' ')+'.';assert.doesNotThrow(()=>compile(input,sources));}});
